import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

export default function Home({ date }) {
  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Macbook PRO 16 inch</h1>
        <Image src="/macbook.png" alt="product" width="210" height="140" />
        <h2>$2,999</h2>
        <Link href="/" passHref>
          <button>Add to cart</button>
        </Link>
      </div>
      <footer>
        <p>
          Page built at <strong>{date}</strong>
        </p>
      </footer>
      <style jsx>{`
      strong {
        margin-left: 4px;
      }
        main {
          height:100%;
          background: #f9fafb;
          width: 100%;
        }
        div {
          min-height:90%;
          width: 100%;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
        }
        footer {
          display:flex;
          justify-content: center;
          align-content: center;
           flex-direction: column;
           text-align: center
        }
        h1 {
          margin:0;
          padding: 24px;
        }
        button {
          padding: 8px 16px;
          background: #e5e7eb;
          border: none;
          cursor: pointer;
          border-radius: 4px;
          transition: 0.25s ease;
        }
        button:hover {
          background: #d1d5db;
        }
        button:active {
          background: #BAC1C9;
        }
        .lorin {
            color:red
        `}</style>
    </main>
  );
}

export async function getServerSideProps() {
  function timeout(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }
  const date = new Date().toLocaleString();
  await timeout(3000);
  return { props: { date } };
}
